### PR TITLE
Add Julio Potier

### PR DESCRIPTION
**Pull request by JulioPotier**

### CODE REVIEW

**Comment by aurooba** [comment]
Hi @JulioPotier. Thanks for the PR, however this repo is specifically to sponsor/support individuals contributing to WordPress (through core, make communities, and/or free plugins). It's not a place to promote a premium plugin. 

If you'd like to include a sponsor me or buy me a coffee link, go ahead and add that edit along with a link to a personal website. Thanks for understanding!

**Comment by JulioPotier** [comment]
My bad, I was not promoting anything.
I though this repo was a repo that will list people that are contributing to WordPress in any/multiple way/s.
I was wrong, so, can you explain it again? Actually, I don't get it ^^ Sorry.

**Comment by aurooba** [comment]
No worries, Julio. This is brand new and I'm slowly refining the guidelines. This repository is intended to make a single source to find WordPress contributors (through working on Make Groups like Core, Community, Docs, etc, or plugin developers) that are providing volunteer work (contributions through Make Groups to the WordPress software or its surrounding communities, or through _free_ plugins), and highlighting links to connect with them and support them through financial contribution (sponsorship, donations, buy me coffee, etc). 

Does that help?

**Comment by JulioPotier** [comment]
Yes, so, that's who I am.
I'm part of the Doc team, I have free plugins on repo, I daily and freely help people on our slack, I did more than 10 WordCamps as speaker, etc, etc
This is why I tried to be listed, as a contributor of WordPress.
So, now, I don't get it :o

**Comment by aurooba** [comment]
@JulioPotier awesome! Here are specific recommendations:

- can you link to a personal website that lists your free plugins instead of your premium plugin?
- can you create a donation page either through the GitHub sponsorship program, a givewp donation page on your personal site, or a buymecoffee link that you can link for the sponsorship?

Those two changes will address the issues. :)

**Comment by JulioPotier** [comment]
I can link my WP profile where the plugins are, or my blogs where free stuff is available, I don't list my free plugins anywhere.
Also, I don't want to add a donation link, is this mandatory? Knowing me as a contributor is enough.

**Comment by aurooba** [comment]
@JulioPotier, yes this is **specifically a list for contributors that can be sponsored and provided donations with**. You are absolutely a contributor and your free plugins and the other work you do is a testament to that. :)

**Pull request closed without merging**
